Pandas is a fast, powerful, flexible and easy to use open source data analysis
and Manipulation tool, build on top of the Pythin programming language

In [1]:
import pandas as pd

In [2]:
pd.__version__

'2.0.3'

In [3]:
# Pandas series with python List

In [4]:
lst = [1, 2, 3, 4, 5]
print(lst)

[1, 2, 3, 4, 5]

In [5]:
series = pd.Series(lst)
print(series)
print(type(series))

0    1
1    2
2    3
3    4
4    5
dtype: int64
<class 'pandas.core.series.Series'>

In [7]:
empty = pd.Series()
print(empty)

Series([], dtype: object)

In [9]:
# creating series with custom index
a = pd.Series(['p', 'q', 'r', 's', 't'], index=[10, 11, 12,13, 14])
print(a)

10    p
11    q
12    r
13    s
14    t
dtype: object

In [10]:
a = pd.Series(['p', 'q', 'r', 's', 't'], index=[10, 11, 12,13, 14], name='My Series')
print(a)

10    p
11    q
12    r
13    s
14    t
Name: My Series, dtype: object

In [11]:
scalar_series = pd.Series(0.5)
print(scalar_series)

0    0.5
dtype: float64

In [12]:
scalar_series = pd.Series(0.5, index = [0, 1, 2, 3, 4])
print(scalar_series)

0    0.5
1    0.5
2    0.5
3    0.5
4    0.5
dtype: float64

In [13]:
# Pandas Series with python Dictionary

In [14]:
dict_series = pd.Series({'a': 1, 'b': 2, 'c': 3, 'd': 4, 'e': 5})
print(dict_series)

a    1
b    2
c    3
d    4
e    5
dtype: int64

In [16]:
print(dict_series[0])

1

In [17]:
print(dict_series[0:3])

a    1
b    2
c    3
dtype: int64

In [18]:
print(max(dict_series))

5

In [20]:
dict_series = pd.Series({'p': [1,2,3], 'q': [4,5,6], 'r': 3, 's': 4, 't': 5})
print(dict_series)

p    [1, 2, 3]
q    [4, 5, 6]
r            3
s            4
t            5
dtype: object

***Pandas Data Frame***

In [21]:
import numpy as np

In [22]:
df = pd.DataFrame()
print(df)

Empty DataFrame
Columns: []
Index: []

In [25]:
lst = [[1, 2, 3, 4, 5, 6], [6, 7, 8, 9, 10]]
df = pd.DataFrame(lst)
print(df)

   0  1  2  3   4    5
0  1  2  3  4   5  6.0
1  6  7  8  9  10  NaN

In [26]:
# Dictionary keys repesent Column names
a = [{'a': 1, 'b': 2, 'c': 3}, {'a': 4, 'b': 5, 'c': 6}]

df = pd.DataFrame(a)
print(df)

   a  b  c
0  1  2  3
1  4  5  6

In [29]:
b = {
    'RollNo.':pd.Series([1, 2, 3, 4, 5]),
    'Name':pd.Series(['Alice', 'Bob', 'Charlie', 'David', 'Eve']),
    'Age':pd.Series([20, 21, 22, 23, 24]),
    'Marks':pd.Series([85, 90, 95, 80, 88]),
    'Physics':pd.Series([90, 92, 88, 85, 91])
}
df = pd.DataFrame(b)
print(df)

   RollNo.     Name  Age  Marks  Physics
0        1    Alice   20     85       90
1        2      Bob   21     90       92
2        3  Charlie   22     95       88
3        4    David   23     80       85
4        5      Eve   24     88       91

***Reading data from csv file***

In [30]:
df = pd.read_csv(r'C:\Users\HRSHUKL\Downloads\Salary_Data.csv')
df

    YearsExperience    Salary
0               1.1   39343.0
1               1.3   46205.0
2               1.5   37731.0
3               2.0   43525.0
4               2.2   39891.0
5               2.9   56642.0
6               3.0   60150.0
7               3.2   54445.0
8               3.2   64445.0
9               3.7   57189.0
10              3.9   63218.0
11              4.0   55794.0
12              4.0   56957.0
13              4.1   57081.0
14              4.5   61111.0
15              4.9   67938.0
16              5.1   66029.0
17              5.3   83088.0
18              5.9   81363.0
19              6.0   93940.0
20              6.8   91738.0
21              7.1   98273.0
22              7.9  101302.0
23              8.2  113812.0
24              8.7  109431.0
25              9.0  105582.0
26              9.5  116969.0
27              9.6  112635.0
28             10.3  122391.0
29             10.5  121872.0

In [31]:
type(df)

pandas.core.frame.DataFrame

***Pandas DataFrame Functions | df.head() | df.tail()***

In [32]:
import pandas as pd

In [33]:
df = pd.read_csv(r'C:\Users\HRSHUKL\Downloads\Salary_Data.csv')

In [34]:
df.head()

   YearsExperience   Salary
0              1.1  39343.0
1              1.3  46205.0
2              1.5  37731.0
3              2.0  43525.0
4              2.2  39891.0

In [37]:
df.columns

Index(['YearsExperience', 'Salary'], dtype='object')

In [38]:
df.shape

(30, 2)

In [39]:
df.size

60

In [41]:
df.tail()

    YearsExperience    Salary
25              9.0  105582.0
26              9.5  116969.0
27              9.6  112635.0
28             10.3  122391.0
29             10.5  121872.0

In [42]:
df.describe()

       YearsExperience         Salary
count        30.000000      30.000000
mean          5.313333   76003.000000
std           2.837888   27414.429785
min           1.100000   37731.000000
25%           3.200000   56720.750000
50%           4.700000   65237.000000
75%           7.700000  100544.750000
max          10.500000  122391.000000

In [43]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 2 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   YearsExperience  30 non-null     float64
 1   Salary           30 non-null     float64
dtypes: float64(2)
memory usage: 612.0 bytes

In [44]:
df2 = pd.read_csv(r'C:\Users\HRSHUKL\Downloads\Restaurant.csv')
df2

,Rank,Restaurant,Content,Sales,YOY_Sales,Units,YOY_Units,Headquarters,Segment_Category
0,1,McDonald's,NaN,40412,4.9%,13846,-0.5%,NaN,Quick Service & Burger
1,2,Starbucks,NaN,21380,8.6%,15049,3.0%,NaN,Quick Service & Coffee Cafe
2,3,Chick-fil-A,While Popeyes got a lot of the chicken buzz in...,11320,13.0%,2470,5.0%,NaN,Quick Service & Chicken
3,4,Taco Bell,NaN,11293,9.0%,6766,2.7%,NaN,Quick Service & Mexican
4,5,Burger King,NaN,10204,2.7%,7346,0.2%,NaN,Quick Service & Burger
...,...,...,...,...,...,...,...,...,...
245,246,Rainforest Cafe,NaN,129,-10.4%,18,-5.3%,NaN,Varied Menu
246,247,PDQ,NaN,127,-5.5%,56,-11.1%,NaN,Chicken
247,248,Lupe Tortilla,NaN,127,12.1%,25,8.7%,NaN,Mexican
248,249,Cook-Out Restaurant,NaN,126,10.1%,270,7.1%,NaN,Burger
249,250,Jollibee,NaN,126,15.2%,40,11.1%,NaN,Chicken

In [45]:
df2.head()

,Rank,Restaurant,Content,Sales,YOY_Sales,Units,YOY_Units,Headquarters,Segment_Category
0,1,McDonald's,NaN,40412,4.9%,13846,-0.5%,NaN,Quick Service & Burger
1,2,Starbucks,NaN,21380,8.6%,15049,3.0%,NaN,Quick Service & Coffee Cafe
2,3,Chick-fil-A,While Popeyes got a lot of the chicken buzz in...,11320,13.0%,2470,5.0%,NaN,Quick Service & Chicken
3,4,Taco Bell,NaN,11293,9.0%,6766,2.7%,NaN,Quick Service & Mexican
4,5,Burger King,NaN,10204,2.7%,7346,0.2%,NaN,Quick Service & Burger

In [47]:
df2.shape

(250, 9)

In [49]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 250 entries, 0 to 249
Data columns (total 9 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Rank              250 non-null    int64
 1   Restaurant        250 non-null    object
 2   Content           33 non-null     object
 3   Sales             250 non-null    int64
 4   YOY_Sales         250 non-null    object
 5   Units             250 non-null    int64
 6   YOY_Units         250 non-null    object
 7   Headquarters      52 non-null     object
 8   Segment_Category  250 non-null    object
dtypes: int64(3), object(6)
memory usage: 17.7+ KB

In [52]:
df2.describe()

             Rank        Sales         Units
count  250.000000    250.00000    250.000000
mean   125.500000   1242.74000    850.076000
std     72.312977   3365.22882   2296.151659
min      1.000000    126.00000     13.000000
25%     63.250000    181.00000     85.000000
50%    125.500000    330.00000    207.000000
75%    187.750000    724.75000    555.250000
max    250.000000  40412.00000  23801.000000

### Handling the Null Values

In [53]:
import pandas as pd

In [54]:
df = pd.read_csv(r'C:\Users\HRSHUKL\Downloads\sample.csv')
df.head()

   Roll No.  Physics  Chemistry  Maths  Computer
0         1     56.0       57.0   58.0      59.0
1         2     23.0       24.0   25.0      26.0
2         3     89.0       25.0   26.0      27.0
3         4     45.0       26.0   27.0      28.0
4         5     23.0       27.0   28.0      29.0

In [55]:
df

    Roll No.  Physics  Chemistry  Maths  Computer
0          1     56.0       57.0   58.0      59.0
1          2     23.0       24.0   25.0      26.0
2          3     89.0       25.0   26.0      27.0
3          4     45.0       26.0   27.0      28.0
4          5     23.0       27.0   28.0      29.0
5          6     90.0        NaN   29.0      30.0
6          7     12.0       13.0   14.0      15.0
7          8     78.0       14.0   15.0      16.0
8          9      NaN       15.0   16.0      17.0
9         10     45.0       16.0   17.0      18.0
10        11      NaN       17.0   18.0      19.0
11        12     88.0        NaN   19.0      20.0
12        13     22.0       23.0   24.0      25.0
13        14     90.0        NaN    NaN      42.0
14        15      NaN       43.0   43.0      43.0
15        16     44.0       44.0   44.0      44.0
16        17     45.0       45.0   45.0      45.0
17        18     46.0       46.0   46.0      46.0
18        19     47.0       47.0   47.0      47.0
19        20     48.0       48.0   48.0      48.0
20        21     49.0       49.0   49.0      49.0
21        22     50.0       50.0   50.0      50.0
22        23     51.0       51.0   51.0      51.0
23        24     52.0       52.0   52.0      52.0
24        25     53.0        NaN    NaN      53.0
25        26     54.0       33.0   33.0      54.0
26        27     55.0       34.0   34.0      55.0
27        28     56.0       35.0   35.0       NaN
28        29     57.0       36.0   36.0      66.0
29        30     58.0       37.0   37.0      43.0

In [ ]:
df.isnull() # to check whether there is a null values available or not

    Roll No.  Physics  Chemistry  Maths  Computer
0      False    False      False  False     False
1      False    False      False  False     False
2      False    False      False  False     False
3      False    False      False  False     False
4      False    False      False  False     False
5      False    False       True  False     False
6      False    False      False  False     False
7      False    False      False  False     False
8      False     True      False  False     False
9      False    False      False  False     False
10     False     True      False  False     False
11     False    False       True  False     False
12     False    False      False  False     False
13     False    False       True   True     False
14     False     True      False  False     False
15     False    False      False  False     False
16     False    False      False  False     False
17     False    False      False  False     False
18     False    False      False  False     False
19     False    False      False  False     False
20     False    False      False  False     False
21     False    False      False  False     False
22     False    False      False  False     False
23     False    False      False  False     False
24     False    False       True   True     False
25     False    False      False  False     False
26     False    False      False  False     False
27     False    False      False  False      True
28     False    False      False  False     False
29     False    False      False  False     False

In [ ]:
df.isnull().sum() # by column it will tell how many null values are there

Roll No.     0
Physics      3
Chemistry    4
Maths        2
Computer     1
dtype: int64

In [58]:
df.isnull().sum().sum()

10

# Dropping Rows with NaN values

In [59]:
df.shape

(30, 5)

In [60]:
df2 = df.dropna() # useing this function we cna drop all the rows which are having any NULL values

In [62]:
df2.shape

(22, 5)

##  Dropping Columns with NaN values

In [63]:
df3 = df.dropna(axis = 1) # axis = 1 for columns
df3.shape

(30, 1)

In [ ]:
df.dropna(how='any') #if any row calue is null then remove that row

    Roll No.  Physics  Chemistry  Maths  Computer
0          1     56.0       57.0   58.0      59.0
1          2     23.0       24.0   25.0      26.0
2          3     89.0       25.0   26.0      27.0
3          4     45.0       26.0   27.0      28.0
4          5     23.0       27.0   28.0      29.0
6          7     12.0       13.0   14.0      15.0
7          8     78.0       14.0   15.0      16.0
9         10     45.0       16.0   17.0      18.0
12        13     22.0       23.0   24.0      25.0
15        16     44.0       44.0   44.0      44.0
16        17     45.0       45.0   45.0      45.0
17        18     46.0       46.0   46.0      46.0
18        19     47.0       47.0   47.0      47.0
19        20     48.0       48.0   48.0      48.0
20        21     49.0       49.0   49.0      49.0
21        22     50.0       50.0   50.0      50.0
22        23     51.0       51.0   51.0      51.0
23        24     52.0       52.0   52.0      52.0
25        26     54.0       33.0   33.0      54.0
26        27     55.0       34.0   34.0      55.0
28        29     57.0       36.0   36.0      66.0
29        30     58.0       37.0   37.0      43.0

In [65]:
df.dropna(how='all') #if all row value is null then remove that row

    Roll No.  Physics  Chemistry  Maths  Computer
0          1     56.0       57.0   58.0      59.0
1          2     23.0       24.0   25.0      26.0
2          3     89.0       25.0   26.0      27.0
3          4     45.0       26.0   27.0      28.0
4          5     23.0       27.0   28.0      29.0
5          6     90.0        NaN   29.0      30.0
6          7     12.0       13.0   14.0      15.0
7          8     78.0       14.0   15.0      16.0
8          9      NaN       15.0   16.0      17.0
9         10     45.0       16.0   17.0      18.0
10        11      NaN       17.0   18.0      19.0
11        12     88.0        NaN   19.0      20.0
12        13     22.0       23.0   24.0      25.0
13        14     90.0        NaN    NaN      42.0
14        15      NaN       43.0   43.0      43.0
15        16     44.0       44.0   44.0      44.0
16        17     45.0       45.0   45.0      45.0
17        18     46.0       46.0   46.0      46.0
18        19     47.0       47.0   47.0      47.0
19        20     48.0       48.0   48.0      48.0
20        21     49.0       49.0   49.0      49.0
21        22     50.0       50.0   50.0      50.0
22        23     51.0       51.0   51.0      51.0
23        24     52.0       52.0   52.0      52.0
24        25     53.0        NaN    NaN      53.0
25        26     54.0       33.0   33.0      54.0
26        27     55.0       34.0   34.0      55.0
27        28     56.0       35.0   35.0       NaN
28        29     57.0       36.0   36.0      66.0
29        30     58.0       37.0   37.0      43.0

In [ ]:
df.dropna(inplace=True) # it will replace the values in the original data frame and return it back to us

In [67]:
df.shape

(22, 5)

## Filling the NULL Values

In [68]:
import pandas as pd

In [69]:
df = pd.read_csv(r'C:\Users\HRSHUKL\Downloads\sample.csv')
df.head()

   Roll No.  Physics  Chemistry  Maths  Computer
0         1     56.0       57.0   58.0      59.0
1         2     23.0       24.0   25.0      26.0
2         3     89.0       25.0   26.0      27.0
3         4     45.0       26.0   27.0      28.0
4         5     23.0       27.0   28.0      29.0

In [75]:
df.isnull().sum()

Roll No.     0
Physics      3
Chemistry    4
Maths        2
Computer     1
dtype: int64

In [ ]:
df.fillna(0) # all the null values are filled with zeros or we can fill with any number

    Roll No.  Physics  Chemistry  Maths  Computer
0          1     56.0       57.0   58.0      59.0
1          2     23.0       24.0   25.0      26.0
2          3     89.0       25.0   26.0      27.0
3          4     45.0       26.0   27.0      28.0
4          5     23.0       27.0   28.0      29.0
5          6     90.0        0.0   29.0      30.0
6          7     12.0       13.0   14.0      15.0
7          8     78.0       14.0   15.0      16.0
8          9      0.0       15.0   16.0      17.0
9         10     45.0       16.0   17.0      18.0
10        11      0.0       17.0   18.0      19.0
11        12     88.0        0.0   19.0      20.0
12        13     22.0       23.0   24.0      25.0
13        14     90.0        0.0    0.0      42.0
14        15      0.0       43.0   43.0      43.0
15        16     44.0       44.0   44.0      44.0
16        17     45.0       45.0   45.0      45.0
17        18     46.0       46.0   46.0      46.0
18        19     47.0       47.0   47.0      47.0
19        20     48.0       48.0   48.0      48.0
20        21     49.0       49.0   49.0      49.0
21        22     50.0       50.0   50.0      50.0
22        23     51.0       51.0   51.0      51.0
23        24     52.0       52.0   52.0      52.0
24        25     53.0        0.0    0.0      53.0
25        26     54.0       33.0   33.0      54.0
26        27     55.0       34.0   34.0      55.0
27        28     56.0       35.0   35.0       0.0
28        29     57.0       36.0   36.0      66.0
29        30     58.0       37.0   37.0      43.0

In [78]:
df.fillna({'Physics':'none', 'Chemistry':0, 'Maths':30})

    Roll No. Physics  Chemistry  Maths  Computer
0          1    56.0       57.0   58.0      59.0
1          2    23.0       24.0   25.0      26.0
2          3    89.0       25.0   26.0      27.0
3          4    45.0       26.0   27.0      28.0
4          5    23.0       27.0   28.0      29.0
5          6    90.0        0.0   29.0      30.0
6          7    12.0       13.0   14.0      15.0
7          8    78.0       14.0   15.0      16.0
8          9    none       15.0   16.0      17.0
9         10    45.0       16.0   17.0      18.0
10        11    none       17.0   18.0      19.0
11        12    88.0        0.0   19.0      20.0
12        13    22.0       23.0   24.0      25.0
13        14    90.0        0.0   30.0      42.0
14        15    none       43.0   43.0      43.0
15        16    44.0       44.0   44.0      44.0
16        17    45.0       45.0   45.0      45.0
17        18    46.0       46.0   46.0      46.0
18        19    47.0       47.0   47.0      47.0
19        20    48.0       48.0   48.0      48.0
20        21    49.0       49.0   49.0      49.0
21        22    50.0       50.0   50.0      50.0
22        23    51.0       51.0   51.0      51.0
23        24    52.0       52.0   52.0      52.0
24        25    53.0        0.0   30.0      53.0
25        26    54.0       33.0   33.0      54.0
26        27    55.0       34.0   34.0      55.0
27        28    56.0       35.0   35.0       NaN
28        29    57.0       36.0   36.0      66.0
29        30    58.0       37.0   37.0      43.0

In [79]:
df.fillna(method='ffill')

    Roll No.  Physics  Chemistry  Maths  Computer
0          1     56.0       57.0   58.0      59.0
1          2     23.0       24.0   25.0      26.0
2          3     89.0       25.0   26.0      27.0
3          4     45.0       26.0   27.0      28.0
4          5     23.0       27.0   28.0      29.0
5          6     90.0       27.0   29.0      30.0
6          7     12.0       13.0   14.0      15.0
7          8     78.0       14.0   15.0      16.0
8          9     78.0       15.0   16.0      17.0
9         10     45.0       16.0   17.0      18.0
10        11     45.0       17.0   18.0      19.0
11        12     88.0       17.0   19.0      20.0
12        13     22.0       23.0   24.0      25.0
13        14     90.0       23.0   24.0      42.0
14        15     90.0       43.0   43.0      43.0
15        16     44.0       44.0   44.0      44.0
16        17     45.0       45.0   45.0      45.0
17        18     46.0       46.0   46.0      46.0
18        19     47.0       47.0   47.0      47.0
19        20     48.0       48.0   48.0      48.0
20        21     49.0       49.0   49.0      49.0
21        22     50.0       50.0   50.0      50.0
22        23     51.0       51.0   51.0      51.0
23        24     52.0       52.0   52.0      52.0
24        25     53.0       52.0   52.0      53.0
25        26     54.0       33.0   33.0      54.0
26        27     55.0       34.0   34.0      55.0
27        28     56.0       35.0   35.0      55.0
28        29     57.0       36.0   36.0      66.0
29        30     58.0       37.0   37.0      43.0

In [80]:
df['Physics'].fillna(value=df['Physics'].mean())

0     56.000000
1     23.000000
2     89.000000
3     45.000000
4     23.000000
5     90.000000
6     12.000000
7     78.000000
8     52.814815
9     45.000000
10    52.814815
11    88.000000
12    22.000000
13    90.000000
14    52.814815
15    44.000000
16    45.000000
17    46.000000
18    47.000000
19    48.000000
20    49.000000
21    50.000000
22    51.000000
23    52.000000
24    53.000000
25    54.000000
26    55.000000
27    56.000000
28    57.000000
29    58.000000
Name: Physics, dtype: float64